### ISSUE TITLE
R2modman Config Editor

### ISSUE THREAD

**Issue by SexyNippleKiller** [xoxfaby/BetterUI#1]
Hi. Got a small issue where 1 (under SortOrder) is not visible, as seen in the picture. Unsure if you can do anything about it.
Other than that Great mod!

![2020-09-08](https://user-images.githubusercontent.com/21283553/92418303-1eddcf80-f167-11ea-956c-ffc318d6b7bb.png)

**Comment by xoxfaby** [comment]
Hmm that's interesting. The R2modmanager seems to expand the description A LOT. that is a lot of empty lines. I would maybe suggest to ask them about it. 

Until then you can just open the config file and see it in there.

**Comment by xoxfaby** [comment]
Fixed in https://github.com/ebkr/r2modmanPlus by https://github.com/ebkr/r2modmanPlus/pull/285

**Comment by SexyNippleKiller** [comment]
Nice. Thank you for the help :)

> Fixed in https://github.com/ebkr/r2modmanPlus by [ebkr/r2modmanPlus#285](https://github.com/ebkr/r2modmanPlus/pull/285)
