### ISSUE TITLE
Void Item config options

### ISSUE THREAD

**Issue by u-lulu** [xoxfaby/BetterUI#100]
**What feature would you like added to BetterUI?**

Currently, BetterUI's configuration files do several things with item tiers, such as allowing items to be sorted by tier, or counting items by tier individually with item counters. The tier that is notably missing is Void items; you can't choose where they show up in sort order, you can't make a separate tiered item counter for them, and I don't think you can even make them add to the total item sum without making hidden items do the same. Having better control over how BUI treats void items would be very nice.

**Comment by xoxfaby** [comment]
Yes this is planned for when I add support for custom itemtierdefs as well.
