### ISSUE TITLE
Old Guillotine shows incorrect threshold value based on item description

### ISSUE THREAD

**Issue by InQuognito** [xoxfaby/BetterUI#102]
![image](https://user-images.githubusercontent.com/44120299/160289573-e1f48cdd-f6e6-4819-a26c-ad88a1233ca8.png)

**Comment by xoxfaby** [comment]
This is the correct value, the vanilla description is inaccurate. If you want to continue the discussion about replacing vanilla descriptions, please keep it in the same issue
