### ISSUE TITLE
Some itemstats are wrong

### ISSUE THREAD

**Issue by GZH2022** [xoxfaby/BetterUI#103]
Fuel Cell and Stone Flux Pauldron
![电池](https://user-images.githubusercontent.com/102461458/160309212-ec4eb2a7-0775-41af-9509-9b9f3350f0c2.png)
![石肩](https://user-images.githubusercontent.com/102461458/160309218-68cd6d7e-8c64-4e4a-8a89-bc91dfc9ecdc.png)

**Comment by xoxfaby** [comment]
Fuel Cell is fixed by c9f3ab2
Stone Flux Pauldron info is correct
