### ISSUE TITLE
Weeping Fungus stat display is wrong

### ISSUE THREAD

**Issue by Rafii2198** [xoxfaby/BetterUI#106]
**Describe the bug**
The problem comes in with the in-game description for Wungus as it states 2%/s which is not true. It actually gives 1%/s. I found it by giving myself 5 Wungi and dropping my hp to 1, in this scenario I would regenerate my hp to full in 10 seconds but it didn't happen, I had around 65% of HP, I assume this is because not only Wungus was healing me but also normal regeneration and by some calculations I did, removing that factor made Weeping Fungus heal for exactly 1%/s.
The other way to test it is that if you have 2 stacks in Void Fields, you would survive while sprinting as it would heal you for 4%/s and Void damage deals 2.5%/s and similarly, this is not the case, you are very slowly dying suggesting you are losing 0.5% of max hp per second.

Now, BetterUI stat display show that incorrect number of 2% so I would suggest changing it to the real 1% value per stack as it is misleading.

*(in unpublished version of ItemStatsMod, it was corrected with an information in the description of the item that the in-game description is incorrect, so it is not only me that found it)*

**BetterUI Version**
2.5.6

**Comment by breadguy69** [comment]
the in game description is just from the vanilla logbook, and the void fields damage scales up

**Comment by Rafii2198** [comment]
I know about the description but I was talking about the stat display. Also void damage deals more damage only if you stayed there too long, the 2.5% of max hp is always base damage regardless of your lvl or time spent in the run. And besides, I used Developer Toolkit to give myself this items and go to void fields so it wasn't normal run.

**Comment by Rafii2198** [comment]
Ok, just to be certain I just conducted exactly same experiment and I was surprised that it perhaps was fixed! Now that I am thinking about it I might tested it before the patch and maybe it was bugged and they didn't said they fixed it in patched notes.
Either way, I need to apologize for false claims, and thus suggesting false information.
