### ISSUE TITLE
Item stats not showing

### ISSUE THREAD

**Issue by BitzThe8Bit** [xoxfaby/BetterUI#109]
Picking up an item will give it the normal vanilla item description, "his music was electric", etc.

[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/8405749/LogOutput.log)

The error occurs with no other mods enabled.

The version I've been using is the latest, 2.5.6.

The config for Item stats does not show up on the mod manager, neither in the files, I've also attempted uninstalling it and installing it again.

**Comment by xoxfaby** [comment]
Does the rest of the mod work?

**Comment by BitzThe8Bit** [comment]
Yes, however, before I go any farther, are the item stats supposed to _only_ appear when using the scrapper? I forgot to add that in the bug report.

**Comment by xoxfaby** [comment]
The main place for them to show is if you hover of them in the scoreboard ( hold tab ). If you want more detailed descriptions when you pick items up, those need to be enabled separately, I believe it's in the Misc, file. There is no option to calculated stats there (yet), but you can see the more detailed description.

**Comment by BitzThe8Bit** [comment]
That's the problem, they don't show the stats in the scoreboard, only vanilla, however, I will look through the misc folder to see if something somehow disabled.

**Comment by xoxfaby** [comment]
did you install this through a profile code?

**Comment by BitzThe8Bit** [comment]
I installed it through Thunderstore mod manager.

**Comment by BitzThe8Bit** [comment]
I think the problem stems to something on the mod manager's side, since the config for item stats simply does not show up anywhere in the files.

**Comment by xoxfaby** [comment]
There is no config specifically for itemstats, there is just an option to disable it under AdvancedIcons

**Comment by xoxfaby** [comment]
and under misc to turn on detailed descriptions

**Comment by BitzThe8Bit** [comment]
I turned on advanced descriptions for both equipment and Items, they were disabled before, however, that still didn't fix the issue. I'm going to see if I missed _another_ config option.

**Comment by xoxfaby** [comment]
Likely one in the Components config that disables that part entirely

**Comment by BitzThe8Bit** [comment]
That did it, Thank you! Sorry for wasting your time with my sheer ignorance.

**Comment by xoxfaby** [comment]
I'm just confused, did you go in and disable these and then forget?

**Comment by BitzThe8Bit** [comment]
Yes, I think because I confused StatDisplay with the Item Stats.

**Comment by BitzThe8Bit** [comment]
Which was something I didn't want
