### ISSUE TITLE
Stone Flux Pauldron health increase not calculated for bison steak

### ISSUE THREAD

**Issue by BLucky-gh** [xoxfaby/BetterUI#114]
**Describe the bug**
The health increase amplification from stone flux pauldrons is calculated for infusions but not for bison steaks

![image](https://user-images.githubusercontent.com/41377306/162918439-12bc9548-7813-46f7-b23c-cabc4e342a13.png)
![image](https://user-images.githubusercontent.com/41377306/162918379-fa72e534-0742-4e76-88f9-26122a4659e8.png)

**BetterUI Version**
2.5.10

**Comment by xoxfaby** [comment]
I think I fixed this, if I haven't, please reopen this issue

**Comment by BLucky-gh** [comment]
I am no longer able to check if the issue is still there since I have an issue with RoR2 crashing on startup when opened through steam(and r2modman opens through steam), so if anyone else can check that would be appreciated
