### ISSUE TITLE
Items stats that don't scale infinitly aren't calculated properly

### ISSUE THREAD

**Issue by alsimoneau** [xoxfaby/BetterUI#117]
Stacking Focused Convergence more than 3 times doesn't do anything. However, the computed stats still show an increase.
[https://riskofrain2.fandom.com/wiki/Focused_Convergence?so=search#Math](https://riskofrain2.fandom.com/wiki/Focused_Convergence?so=search#Math)

Likewise, Safer Spaces has a minimal cooldown of 1s that is not displayed properly.
[https://riskofrain2.fandom.com/wiki/Safer_Spaces#Math](https://riskofrain2.fandom.com/wiki/Safer_Spaces#Math)

**Comment by xoxfaby** [comment]
Are these still incorrect on the latest version?

**Comment by alsimoneau** [comment]
They are, except the Focused Convergence teleporter zone.
