### ISSUE TITLE
Better UI calculating CDR on skills one pickup later.

### ISSUE THREAD

**Issue by Ner0ls** [xoxfaby/BetterUI#123]
**Describe the bug**
Better UI calculating CDR on skills one pickup later, or one "inventoryChange" later.

**Link your log file**
https://pastebin.com/WPEWk4vf

**Does the error occur when only using BetterUI and no other mods?**
Yes it does, I've loaded the bare minimum:
- BepInEx
- Unity Explorer (For debugging)
- Skip Intro (F waiting lol)
- BetterUI

**BetterUI Version**
2.5.12

**Additional information**
After picking up a CDR item, any pickup will "properly set" CDR on skills, the same behavior occurs with losing a CDR item, it won't update CDR on skills until another refresh of inventory.

Here you can see Alien Head not properly applying the CDR calculations.
![20220428103406_1](https://user-images.githubusercontent.com/38695851/165780985-599b67f3-6d46-4f9b-81e2-2d150a468926.jpg)

One item later, it does:
![20220428103412_1](https://user-images.githubusercontent.com/38695851/165781235-a2ae05c4-6e9c-4927-adeb-14269dd0e980.jpg)

The same when I lose it, it keeps the CDR:
![20220428103658_1](https://user-images.githubusercontent.com/38695851/165781299-31636c74-a4e5-4230-a9e0-64a617fbafd7.jpg)

Until another pickup:
![20220428103725_1](https://user-images.githubusercontent.com/38695851/165781392-f84c1a4d-c34d-4dc7-8ded-0f4ebc4d3ffe.jpg)

Final notes:
- Did not test purity (flat CDR)
- This also happens with modded items registered through R2API

**Comment by xoxfaby** [comment]
I don't remember if I fixed this, if I haven't please reopen this issue.
