### ISSUE TITLE
Game freezes at 100% loading

### ISSUE THREAD

**Issue by zcn15** [xoxfaby/BetterUI#124]
**Describe the bug**
When game start to load it freezes at 100%

**Link your log file**
https://disk.yandex.com/d/seDG_yzfVMznxQ

**Does the error occur when only using BetterUI and no other mods?**
It stops at 100% when with my other mods and when alone

**BetterUI Version**
2.5.12

**Additional information**
Few days ago it was working fine

**Comment by zcn15** [comment]
i disabled "ItemCounters" in config "BetterUI-Components" and now it loads
But in game when item drops on the ground it stay till the end of the game, if i pick up it gives me infinite times.
Bungus dropped i tried to pick it up and i immediately have 300 in my inventory and and he continues to bulge to me with great speed

**Comment by Judgy53** [comment]
Your game is not updated to latest version. Updating it should fix your issue.

**Comment by IonutDaniel99** [comment]
I have latest update on steam and latest r2modman and the problem still persist

**Comment by xoxfaby** [comment]
Log url is not valid, if this problem still exists, please reopen with a new log
