### ISSUE TITLE
Always show cooldown timer for skills/equipment

### ISSUE THREAD

**Issue by RandomNerd1** [xoxfaby/BetterUI#13]
In the vanilla game, if you have multiple charges of a skill or equipment, and not all of them have been depleted, the amount of time before you get your next charge is not displayed. It would be great if you could see, for example, how close you are to getting back a second Preon Accumulator charge (having a Fuel Cell), to know how long you'd be without it if you used the one charge you currently have available.

**Comment by xoxfaby** [comment]
I will have to look into this, it will either be very easy to implement or very difficult, whether or not I do it depends on that,

**Comment by xoxfaby** [comment]
https://gfycat.com/giftedellipticalfunnelweaverspider

Is this about what you were looking for?

**Comment by xoxfaby** [comment]
https://gfycat.com/MediocreAcidicAlleycat

**Comment by RandomNerd1** [comment]
Exactly! :)
