### ISSUE TITLE
softlock

### ISSUE THREAD

**Issue by firestarter2012** [xoxfaby/BetterUI#134]
**Describe the bug**
A clear description of what the bug is.
the game softlocks when you get of the shuttle
**Link your log file**
You can find your log file under `Risk of Rain 2/BepInEx/LogOutput.log`

**Does the error occur when only using BetterUI and no other mods?** yes it does
Please test this before submitting a bug report. 
i did it happens to all survivers 
**BetterUI Version**
Which version of BetterUI you're using e.g.: v1.2.1

**Additional information**

**Comment by xoxfaby** [comment]
Please follow the bug template.
