### ISSUE TITLE
Can't use the cutmmando skin mod with BetterUI

### ISSUE THREAD

**Issue by omeggga** [xoxfaby/BetterUI#139]
**Describe the bug**
When having the cutmando mod and better UI installed. If I do that the third skin simply dows not appear in the character/skill selection menu.

**Does the error occur when only using BetterUI and no other mods?**
Disabling BetterUI makes the third skin appear.

**BetterUI Version**
2.6.1

**Additional information**
Cutmando can be found here: https://thunderstore.io/package/Slipskip/CutMandoSkin/

**Comment by xoxfaby** [comment]
Please do not remove random parts of the bug template.

**Comment by xoxfaby** [comment]
For the record, you are very welcome to reopen this issue with the missing info attached but the requested info is there for a reason.
