### ISSUE TITLE
StatsDisplay does not work in any of the Hidden Realms.

### ISSUE THREAD

**Issue by g0shu** [xoxfaby/BetterUI#14]
**Describe the bug**
Noticed it was missing in the Bazaar, upon further investigation it was missing from [all of them](https://riskofrain2.gamepedia.com/Environments#Hidden_Realms), and also on the moon.

**What other mods do you use**
Tested on a fresh profile.

**BetterUI Version**
1.4.0

**Additional information**
A minor suggestion not deserving its own issue, how about capping crit chance display at 100%?

**Comment by xoxfaby** [comment]
>A minor suggestion not deserving its own issue, how about capping crit chance display at 100%?

It's uncapped on purpose for use with mods such as Hypercrit and I see nothing gained by artificially capping it. If anything people should know if they went over.

**Comment by g0shu** [comment]
Ah, makes sense. 
I think you accidentally committed a log file https://github.com/xoxfaby/BetterUI/blob/master/BetterUI/Thunderstore/LogOutput%20-%20Copy.log.txt

**Comment by xoxfaby** [comment]
shh, never happened
