### ISSUE TITLE
BetterUI options in main menu

### ISSUE THREAD

**Issue by Artie-cool** [xoxfaby/BetterUI#140]
BetterUI v2.6.1

When in main menu I can see new button called BETTERUI_TITLE. This button does nothing...

I'm new to ROR2 modding, so please tell me if I'm doing something wrong, or maybe I need some addition mod.

Also I'm using XSplitScreen by dodat v1.2.1 and when I enter XSplitScreen menu (in mine menu) BetterUI info (like diskord etc) is popping up.

Tell me if I'm doing something wrong...

**Comment by xoxfaby** [comment]
Please follow the bug template
