### ISSUE TITLE
Prismatic Trial not available

### ISSUE THREAD

**Issue by KurodaAkira** [xoxfaby/BetterUI#145]
Whenever I launch the game while having the mod activated, the Prismatic Trial alternative game mode isn't available.
The button for it doesn't appear in the game.
If I launch the game without the mod, the button is there.

**Comment by Judgy53** [comment]
This is not an issue with BetterUI specifically, prismatic trials are disabled for modded clients because RoR2 devs want the global leaderboard to be fair for everyone.

PS: Please follow the bug report template when submitting an issue.
