### ISSUE TITLE
Host cannot see teammate's money in Tab Menu

### ISSUE THREAD

**Issue by explojoe** [xoxfaby/BetterUI#148]
Host cannot see teammate's money in Tab Menu

Reproduction: press tab as host with 2 players in game. Host sees no money. Clients see money.
![image](https://user-images.githubusercontent.com/6623025/204629705-76ce8efd-1858-46d5-8b93-777bed979419.png)

**Comment by xoxfaby** [comment]
Please follow the bug report template

**Comment by explojoe** [comment]
Sorry about that, I'll make a proper one.
