### ISSUE TITLE
Command mod restriction problem

### ISSUE THREAD

**Issue by EmuLegs** [xoxfaby/BetterUI#15]
**Describe the bug**
From what i can tell the new command menu offers items the player has yet to pick up.

https://imgur.com/a/qw2ibGg

**Comment by xoxfaby** [comment]
I specifically coded the hook to preserve the availability of each item so this *shouldn't* happen.

**Comment by EmuLegs** [comment]
sure, i only have 1 item that i have not seen and that item is a Blue, this may have an effect somwhere
https://imgur.com/a/rv0ig21

**Comment by EmuLegs** [comment]
Happens in Solo and multiplayer
https://imgur.com/a/chqivVc

**Comment by xoxfaby** [comment]
Can you contact me on discord?

**Comment by xoxfaby** [comment]
I can not reproduce this. If you are still experiencing this, feel free to contact me and reopen this, but for now I just have not been able to replicate this bug so I will be closing the issue until more information is gathered.

**Comment by EmuLegs** [comment]
Sure heres my server 
https://discord.gg/mVK2qQ
and my profile link
EmuLegs#0053
