### ISSUE TITLE
Changing language makes text on the BetterUI Window in the main menu broken

### ISSUE THREAD

**Issue by Lienep0** [xoxfaby/BetterUI#150]
*If you submit an incomplete bug report that doesn't follow this template completely, it will be closed without reading until you update the bug report with the missing info*

**Describe the bug**  
Self-explanatory.

**Link your log file**  
I can't, I'm using r2modman

**Does the error occur when only using BetterUI and no other mods?**  
Yes it does

**BetterUI Version**  
v2.6.4

**Comment by XaHTePo** [comment]
i changed filename from en.json to needed language.json
for me - fixed, but, of course, not changed anything
then relloading the game fixes itself)
if you use default - setting "default.json" not helps

my path to this file)
AppData\Roaming\Thunderstore Mod Manager\DataFolder\RiskOfRain2\profiles\Default\BepInEx\plugins\XoXFaby-BetterUI

**Comment by xoxfaby** [comment]
Provide a log on the latest version or I have to close this as can not reproduce

**Comment by XaHTePo** [comment]
> Provide a log on the latest version or I have to close this as can not reproduce

[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/10230421/LogOutput.log)

this is what you need or must i close game for creating a new one?)

**Comment by XaHTePo** [comment]
can you explain where and when i need to find it?

**Comment by xoxfaby** [comment]
Oh, this was fixed a few patch ago. also, all your file name changing did nothing. please don't change the names of those files unless you're trying to do something specific, they have the correct names.
