### ISSUE TITLE
Fully translatable

### ISSUE THREAD

**Issue by Damglador** [xoxfaby/BetterUI#151]
I see that new window in main menu can be translated. I got it when downloaded mod and saw tokens on buttons instead of text bcs I'm working on unofficial Ukrainian translation. And I think would be cool if entire mod was translatable, not only this window, also availability of translation files in mod like a folder.

**Comment by xoxfaby** [comment]
I can look into the best format for supplying translations. While it is unlikely I would be doing any translations myself, I would be open to accept Pull Requests that add them.
