### ISSUE TITLE
Most recent update seems to have broken the mod

### ISSUE THREAD

**Issue by BuckAMayzing** [xoxfaby/BetterUI#152]
I'm not 100% sure on this, but updating to v2.7.0 seems to have broken the mod - I don't see the menu anymore, though the console doesn't seem to give an indication as to what may have broken.

**Comment by xoxfaby** [comment]
This is due to the way r2modman unpacks files, I'm working on a hotfix

**Comment by BuckAMayzing** [comment]
Gotcha. Temporary workaround in case someone else finds it:

Create the following folder: 

`C:\Users\{your username}\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\plugins\XoXFaby-BetterUI\Languages`
