### ISSUE TITLE
Non-host players cannot see timer on buffs/debuffs

### ISSUE THREAD

**Issue by Hammerkirby123** [xoxfaby/BetterUI#157]
When I am playing multiplayer with my friend, I cannot see the time left I have on buffs

We have no other mods that will change how buffs are displayed, we even tested it with just that mod and its dependencies

better UI version 2.7.4

[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/10280971/LogOutput.log)

**Comment by xoxfaby** [comment]
As it says in the readme:

> Buff timers currently only work if you are the host because the timers are not networked in multiplayer.
