### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by Fiocher** [xoxfaby/BetterUI#159]
I'm a RoR2 player from China and love BetterUI mod, so it took me a while to localize.
Translation completed, but the statistical list on the right cannot be translated, and there is no relevant code in the json file that can be translated.

**The following is the translation of the statistical list:**
Stats=统计
Luck=幸运值
Experience=经验值
Base Damage=基础伤害
Crit Chance=暴击几率
Crit w/ Luck=暴击几率修正
Crit Damage=暴击伤害倍率
Attack Speed=攻击速度
Armor=护甲
Regen=回复
Speed=当前速度
Jumps=跳跃次数
Kills=击杀数量
Mountain Shrines=山之挑战
Difficulty=难度
Blue Portal=蓝色传送门
Gold Portal=金色传送门
Celestial Portal=天界传送门
Void Portal=虚空传送门
False=未激活
True=已激活

**Preview:**
![Snipaste_2022-12-23_12-13-38](https://user-images.githubusercontent.com/82749343/209276360-545e4304-458c-4ee8-8b93-0cfea07de373.png)
![Snipaste_2022-12-23_10-51-50](https://user-images.githubusercontent.com/82749343/209276390-5e0fa493-4a00-42ac-926f-fca6cfa36f8e.png)
![Snipaste_2022-12-23_12-12-03](https://user-images.githubusercontent.com/82749343/209276397-1e1f1c17-5dad-4815-a7a9-a140230b892e.png)
![Snipaste_2022-12-23_12-15-10](https://user-images.githubusercontent.com/82749343/209276399-0f2f3877-cb12-4d0d-8f58-70586aa8730f.png)
![Snipaste_2022-12-23_12-59-43](https://user-images.githubusercontent.com/82749343/209276403-adbd23bd-3470-4003-af55-6557ce3ade7b.png)
![Snipaste_2022-12-23_12-14-40](https://user-images.githubusercontent.com/82749343/209276419-cd518ae7-3682-4843-9b8c-2651063fcbb5.png)

**File:**
[zh_cn.zip](https://github.com/xoxfaby/BetterUI/files/10292285/zh_cn.zip)

**Comment by Damglador** [comment]
Stats tab cant be translated, strings not implemented yet. Also you can create pull request, it would be better

**Comment by xoxfaby** [comment]
I've added your translations. If you would like credit in the Readme (for an example see Ukranian patch notes, let me know.

**Comment by xoxfaby** [comment]
Thank you for your contribution

**Comment by xoxfaby** [comment]
Also @Fiocher I'm going to need you to read and sign our [Contributor License Agreement](https://github.com/xoxfaby/BetterUI/blob/master/CLA.md)

You can sign the CLA by just by adding a comment to this pull request with this exact sentence:

> I have read the CLA Document and I hereby sign the CLA

By commenting with the above message you are agreeing to the terms of the CLA.

**Comment by xoxfaby** [comment]
👍

Let me know if you want credit in the readme by name and which name

Something like "Added Chinese Translations: Thanks Fiocher"

**Comment by xoxfaby** [comment]
Okay, so it would be 

> Added Chinese Translations ( Thanks 南家老树皮 )

Also, if you are willing to help with future translation (if BetterUI adds more strings and they would need to be translated as well), then please join the discord at https://discord.faby.dev and ping in github discussion
