### ISSUE TITLE
$luckcrit showing incorrect values

### ISSUE THREAD

**Issue by RandomNerd1** [xoxfaby/BetterUI#16]
**Describe the bug**
The new variable isn't showing the correct values for crit chance taking luck into account, for both positive and negative luck. In case there's some dumb syntax error on my part, here's the string I use for the stats display:

`<color=#FFFFFF><size=16><b>Stats</b></size>\n<size=12>Luck: $luck\nBase Damage: $dmg\nCrit Chance: $luckcrit\nAttack Speed: $atkspd\nArmor: $armor | $armordmgreduction%\nRegen: $regen\nSpeed: $movespeed\nJumps: $jumps/$maxjumps\nKills: $killcount\nMountain Shrines: $mountainshrines\nBlue Portal: $blueportal\nGold Portal: $goldportal\nCelestial Portal: $celestialportal\n`

**What other mods do you use**
Here's my r2modman profile code: HDAEGa7fGT
If you REALLY need all 18 typed out individually, let me know, lol...it'd be a pain to do.

**BetterUI Version**
1.4.4

**Additional information**
Screenshot of what I see with -1 Luck: https://steamuserimages-a.akamaihd.net/ugc/1625193482302168998/7F5F7F538D9B8B65834913FCBB75774A13B2602C/
Screenshot of what I see with +1 Luck: https://steamuserimages-a.akamaihd.net/ugc/1625193482302176664/83196F317B9D9106C0AD4F492DC39C41C03B0C27/

**Comment by xoxfaby** [comment]
For future reference, if you include log file that also includes your list of mods.

**Comment by RandomNerd1** [comment]
This?

`﻿[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 18 plugins to load
[Info   :   BepInEx] Loading [R2API 2.5.14]
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.UnitySystemConsoleRedirector.Redirect
[Info   :     R2API] Enabling R2API Submodule: LanguageAPI
[Info   :     R2API] Enabling R2API Submodule: PrefabAPI
[Info   :     R2API] Enabling R2API Submodule: ResourcesAPI
[Info   :     R2API] Enabling R2API Submodule: CommandHelper
[Info   :     R2API] Enabling R2API Submodule: NetworkingAPI
[Debug  :     R2API] Hook added by assembly: R2API.dll for: UnityEngine.Resources.Load
[Debug  :     R2API] Hook added by assembly: R2API.dll for: UnityEngine.Resources.LoadAsyncInternal
[Debug  :     R2API] Hook added by assembly: R2API.dll for: UnityEngine.Resources.LoadAll
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Console.InitConVars
[Debug  :     R2API] LanguageAPI has no static method registered for Load
[Debug  :     R2API] PrefabAPI has no static method registered for Load
[Debug  :     R2API] ResourcesAPI has no static method registered for Load
[Debug  :     R2API] CommandHelper has no static method registered for Load
[Debug  :     R2API] NetworkingAPI has no static method registered for Load
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.DisableIfGameModded.OnEnable
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Debug  :     R2API] Hook added by assembly:  for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Info   :   BepInEx] Loading [FastScrapper 1.1.0]
[Debug  :     R2API] Hook added by assembly: FasterScrapper.dll for: RoR2.Stage.Start
[Debug  :     R2API] Hook added by assembly: FasterScrapper.dll for: RoR2.ScrapperController.Start
[Info   :   BepInEx] Loading [NoKick 1.0.1]
[Debug  :     R2API] Hook added by assembly: NoKick.dll for: RoR2.CharacterMaster.OnBodyStart
[Debug  :     R2API] Hook added by assembly: NoKick.dll for: EntityStates.NewtMonster.KickFromShop.OnEnter
[Info   :   BepInEx] Loading [LunarCoinShareOnPickup 3.6.1]
[Debug  :     R2API] Hook added by assembly: LunarCoinShareOnPickup.dll for: RoR2.GenericPickupController.OnInteractionBegin
[Info   :   BepInEx] Loading [EmptyChestsBeGone 1.1.0]
[Debug  :     R2API] Hook added by assembly: EmptyChestsBeGone.dll for: EntityStates.Barrel.Opened.OnEnter
[Info   :   BepInEx] Loading [Faster3DPrinters 1.0.0]
[Debug  :     R2API] Hook added by assembly: Faster3DPrinters.dll for: RoR2.Stage.Start
[Debug  :     R2API] Hook added by assembly: Faster3DPrinters.dll for: EntityStates.Duplicator.Duplicating.DropDroplet
[Debug  :     R2API] Hook added by assembly: Faster3DPrinters.dll for: EntityStates.Duplicator.Duplicating.BeginCooking
[Info   :   BepInEx] Loading [RTAutoSprintEx 1.1.2]
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.Flamethrower.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.Flamethrower.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.PrepWall.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.PrepWall.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.FireFireBolt.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Mage.Weapon.FireLaserbolt.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Engi.EngiWeapon.FireMines.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Engi.EngiWeapon.FireSeekerGrenades.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Engi.EngiMissilePainter.Paint.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Engi.EngiMissilePainter.Paint.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.FireNailgun.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.FireNailgun.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Toolbot.FireGrenadeLauncher.PlayAnimation
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Toolbot.AimGrenade.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Toolbot.RecoverAimStunDrone.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Toolbot.StartToolbotStanceSwap.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Treebot.Weapon.FireSyringe.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Treebot.Weapon.AimMortar.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Treebot.Weapon.AimMortar.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Treebot.Weapon.AimMortar2.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Treebot.Weapon.AimMortar2.OnProjectileFiredLocal
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Croco.Slash.PlayAnimation
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Commando.CommandoWeapon.FirePistol2.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Loader.SwingComboFist.PlayAnimation
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Captain.Weapon.SetupAirstrike.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Captain.Weapon.SetupAirstrike.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Captain.Weapon.SetupSupplyDrop.OnEnter
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: EntityStates.Captain.Weapon.SetupSupplyDrop.OnExit
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: RoR2.PlayerCharacterMasterController.OnEnable
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: RoR2.PlayerCharacterMasterController.FixedUpdate
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: RoR2.CameraRigController.Update
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: RoR2.UI.CrosshairManager.UpdateCrosshair
[Info   : Unity Log] RtAutoSprintEx: Disabling sprinting crosshair:
[Debug  :     R2API] Hook added by assembly:  for: RoR2.UI.CrosshairManager.UpdateCrosshair
[Debug  :     R2API] Hook added by assembly: RTAutoSprintEx.dll for: RoR2.CameraRigController.Update
[Info   : Unity Log] RtAutoSprintEx: Modifying Sprint FOV Multiplier:
[Info   : Unity Log] RtAutoSprintEx: CameraRigController.Update IL edits done.
[Debug  :     R2API] Hook added by assembly:  for: RoR2.CameraRigController.Update
[Info   :   BepInEx] Loading [StartingItemsGUI 1.2.2]
[Error  : Unity Log] Script error (StartingItemsGUI): OnEnable() can not take parameters.
[Info   :   BepInEx] Loading [Proper Save 2.4.5]
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: Phedg1Studios.StartingItemsGUI.StartingItemsGUI.OnRunStartGlobal
[Debug  :     R2API] Hook added by assembly:  for: Phedg1Studios.StartingItemsGUI.StartingItemsGUI.OnRunStartGlobal
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.Run.Start
[Debug  :     R2API] Hook added by assembly:  for: RoR2.Run.Start
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.TeamManager.Start
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.Achievements.LoopOnceAchievement.Check
[Debug  :     R2API] Hook added by assembly:  for: RoR2.Achievements.LoopOnceAchievement.Check
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.Stage.Start
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.GameOverController.Awake
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.Run.GenerateStageRNG
[Debug  :     R2API] Hook added by assembly: ProperSave.dll for: RoR2.UI.CharacterSelectController.Awake
[Info   :   BepInEx] Loading [ItemExchangeNotifier 1.3.1]
[Debug  :     R2API] Hook added by assembly: ItemExchangeNotifier.dll for: RoR2.PurchaseInteraction.OnInteractionBegin
[Info   :   BepInEx] Loading [Pingprovements 1.7.0]
[Debug  :     R2API] Hook added by assembly: Pingprovements.dll for: RoR2.PingerController.SetCurrentPing
[Debug  :     R2API] Hook added by assembly: Pingprovements.dll for: RoR2.UI.PingIndicator.Update
[Info   :   BepInEx] Loading [Yeet 1.2.0]
[Debug  :     R2API] Hook added by assembly: Yeet.dll for: RoR2.UI.ItemIcon.Awake
[Debug  :     R2API] Hook added by assembly: Yeet.dll for: RoR2.UI.EquipmentIcon.Update
[Info   :   BepInEx] Loading [ItemStats 2.0.0]
[Debug  :     R2API] Hook added by assembly: ItemStats.dll for: RoR2.UI.HUD.Update
[Debug  :     R2API] Hook added by assembly: ItemStats.dll for: RoR2.UI.ScoreboardStrip.SetMaster
[Debug  :     R2API] Hook added by assembly: ItemStats.dll for: RoR2.UI.GenericNotification.SetItem
[Debug  :     R2API] Hook added by assembly: ItemStats.dll for: RoR2.UI.ItemInventoryDisplay.AllocateIcons
[Debug  :     R2API] Hook added by assembly: ItemStats.dll for: RoR2.UI.ItemIcon.SetItemIndex
[Info   :   BepInEx] Loading [BetterUI 1.4.4]
[Debug  :     R2API] Hook added by assembly: 0Harmony.dll for: BepInEx.Configuration.ConfigFile.Reload
[Debug  :     R2API] Hook added by assembly:  for: BepInEx.Configuration.ConfigFile.Reload
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.ItemIcon.SetItemIndex
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.EquipmentIcon.Update
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.GenericNotification.SetItem
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.GenericNotification.SetEquipment
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.SetPickupOptions
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.Awake
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.OnCreateButton
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.GlobalEventManager.ClientDamageNotified
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.ItemInventoryDisplay.OnInventoryChanged
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.BuffIcon.Awake
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.BuffIcon.UpdateIcon
[Debug  :     R2API] Hook added by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
[Info   :   BepInEx] Loading [ShowDeathCause 1.0.4]
[Debug  :     R2API] Hook added by assembly: ShowDeathCause.dll for: RoR2.GlobalEventManager.OnPlayerCharacterDeath
[Info   :   BepInEx] Loading [MiniRpcLib 1.1]
[Info   :MiniRpcLib] Initializing Logger
[Info   :MiniRpcLib] Initializing MiniRpc
[Debug  :     R2API] Hook added by assembly: MiniRpcLib.dll for: RoR2.Networking.NetworkMessageHandlerAttribute.CollectHandlers
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   :   BepInEx] Loading [UnmoddedVersion 1.0.1]
[Debug  :     R2API] Hook added by assembly: UnmoddedVersion.dll for: RoR2.RoR2Application.GetBuildId
[Debug  :     R2API] Hook added by assembly:  for: RoR2.RoR2Application.GetBuildId
[Debug  :     R2API] Hook added by assembly: UnmoddedVersion.dll for: RoR2.NetworkModCompatibilityHelper.get_networkModList
[Debug  :     R2API] Hook added by assembly: UnmoddedVersion.dll for: RoR2.NetworkModCompatibilityHelper.set_networkModList
[Info   :   BepInEx] Loading [Better Mod Mismatch info 1.0.0.0]
[Debug  :     R2API] Hook added by assembly: BetterModMismatchInfo.dll for: RoR2.Networking.GameNetworkManager+SimpleLocalizedKickReason.GetDisplayTokenAndFormatParams
[Debug  :     R2API] Hook added by assembly: BetterModMismatchInfo.dll for: RoR2.UnitySystemConsoleRedirector.Redirect
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] Network message MsgType.Highest + 22 is unregistered.
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   :   Console] Searching for compatible XInput library...
[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Bloom: True
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] 0
[Info   : Unity Log] arg[0]="C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
[Info   : Unity Log] arg[1]="--doorstop-enable"
[Info   : Unity Log] arg[2]="true"
[Info   : Unity Log] arg[3]="--doorstop-target"
[Info   : Unity Log] arg[4]="r2modman\BepInEx\core\BepInEx.Preloader.dll"
[Info   : Unity Log] Initializing system: ArtifactCatalog
[Info   : Unity Log] Initializing system: BodyCatalog
[Info   : Unity Log] Initializing system: BuffCatalog
[Warning: Unity Log] Unregistered buff CrocoRegen!
[Warning: Unity Log] Unregistered buff MercExpose!
[Warning: Unity Log] Unregistered buff BodyArmor!
[Info   : Unity Log] Initializing system: CostTypeCatalog
[Info   : Unity Log] Initializing system: GameEndingCatalog
[Info   : Unity Log] Initializing system: EffectCatalog
[Error  : Unity Log] Error registering effect "DroneFlamethrowerEffect (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
[Error  : Unity Log] Error registering effect "FireMeatBallPool (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
[Error  : Unity Log] Error registering effect "LunarWispTrackingBombExp_Prf (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
[Error  : Unity Log] Error registering effect "LunarWispMinigunChargeUp (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
[Error  : Unity Log] Error registering effect "SiphonTetherHealing (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
[Info   : Unity Log] Initializing system: EliteCatalog
[Info   : Unity Log] Initializing system: EquipmentCatalog
[Info   : Unity Log] Initializing system: FileIoIndicatorManager
[Info   : Unity Log] Initializing system: DebugOverlay
[Info   : Unity Log] Initializing system: GenericPickupController
[Info   : Unity Log] Initializing system: NetworkUIPromptController
[Info   : Unity Log] Initializing system: PickupDropletController
[Info   : Unity Log] Initializing system: RunArtifactManager
[Info   : Unity Log] Initializing system: ItemCatalog
[Info   : Unity Log] Initializing system: Language
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Found icon.png
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] Initializing system: MasterCatalog
[Info   : Unity Log] Initializing system: MusicTrackCatalog
[Info   : Unity Log] Initializing system: PickupCatalog
[Info   : Unity Log] Initializing system: PickupTransmutationManager
[Info   : Unity Log] Initializing system: ProjectileCatalog
[Info   : Unity Log] Initializing system: RuleCatalog
[Info   : Unity Log] Initializing system: SceneCatalog
[Info   : Unity Log] Initializing system: SkinCatalog
[Info   : Unity Log] Initializing system: SurvivorCatalog
[Warning: Unity Log] Unregistered survivor Bandit!
[Info   : Unity Log] Initializing system: UnlockableCatalog
[Info   : Unity Log] Initializing system: UserProfile
[Info   : Unity Log] Initializing system: StatDef
[Info   : Unity Log] Initializing system: StatManager
[Info   : Unity Log] Initializing system: StatSheet
[Info   : Unity Log] Initializing system: SkillCatalog
[Info   : Unity Log] Initializing system: EnemyInfoPanel
[Info   : Unity Log] Initializing system: UILayerKey
[Info   : Unity Log] Initializing system: NetworkSoundEventCatalog
[Info   : Unity Log] Initializing system: BombArtifactManager
[Info   : Unity Log] Initializing system: CommandArtifactManager
[Info   : Unity Log] Initializing system: DoppelgangerInvasionManager
[Info   : Unity Log] Initializing system: EnigmaArtifactManager
[Info   : Unity Log] Initializing system: FriendlyFireArtifactManager
[Info   : Unity Log] Initializing system: MonsterTeamGainsItemsArtifactManager
[Info   : Unity Log] Initializing system: SacrificeArtifactManager
[Info   : Unity Log] Initializing system: SwarmsArtifactManager
[Info   : Unity Log] Initializing system: TeamDeathArtifactManager
[Info   : Unity Log] Initializing system: NetworkExtensions
[Info   : Unity Log] Initializing system: AchievementManager
[Info   : Unity Log] Initializing system: ArtifactMask
[Info   : Unity Log] Initializing system: LunarItemOrEquipmentCostTypeHelper
[Info   : Unity Log] Initializing system: ItemDisplayRuleSet
[Info   : Unity Log] Initializing system: PreGameRuleVoteController
[Info   : Unity Log] Initializing system: ShrineCleanseBehavior
[Info   : Unity Log] Initializing system: GameModeCatalog
[Info   : Unity Log] Registered gamemode BaseDefenseRun True
[Info   : Unity Log] Registered gamemode ClassicRun True
[Info   : Unity Log] Registered gamemode EclipseRun True
[Info   : Unity Log] Registered gamemode WeeklyRun True
[Info   : Unity Log] Initializing system: Loadout
[Info   : Unity Log] Initializing system: BodyLoadoutManager
[Info   : Unity Log] Initializing system: ProjectileGhostReplacementManager
[Info   : Unity Log] Initializing system: RuleBook
[Info   : Unity Log] Initializing system: SerializableLoadout
[Info   : Unity Log] Initializing system: SteamworksLobbyDataGenerator
[Info   : Unity Log] Initializing system: LogBookController
[Info   : Unity Log] Initializing system: CharacterSpawnCard
[Info   : Unity Log] Attempting to load user profile /UserProfiles/1d6065f6-d82c-4902-a851-e4222b5d7c81.xml
[Info   : Unity Log] stream.Length=148570
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] 8
[Info   : Unity Log] Loaded archived convars.
[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=2
[Info   :     R2API] [NetworkCompatibility] Adding to the networkModList : 
[Info   :     R2API] com.bepis.r2api;2.5.14
[Info   :     R2API] com.cubeanimataz.FastScrapper;1.1.0
[Info   :     R2API] com.Daar375.NoKick;1.0.1
[Info   :     R2API] com.dan8991iel.LunarCoinShareOnPickup;3.6.1
[Info   :     R2API] com.Elysium.ECBG;1.1.0
[Info   :     R2API] com.Elysium.Fast3D;1.0.0
[Info   :     R2API] com.Phedg1Studios.StartingItemsGUI;1.2.2
[Info   :     R2API] com.pixeldesu.pingprovements;1.7.0
[Info   :     R2API] com.ThinkInvisible.Yeet;1.2.0
[Info   :     R2API] dev.wildbook.libminirpc;1.1
[Info   :     R2API] net.frostycpu.unmoddedversion;1.0.1
[Debug  :     R2API] Hook added by assembly: StartingItemsGUI.dll for: RoR2.PreGameController.OnEnable
[Debug  :     R2API] Hook added by assembly: StartingItemsGUI.dll for: RoR2.CharacterBody.OnDeathStart
[Debug  :     R2API] Hook added by assembly: StartingItemsGUI.dll for: RoR2.UI.ScrollToSelection.ScrollToRect
[Message:Better Mod Mismatch info] Modlist:

[Message:Better Mod Mismatch info] ModHash:D41D8CD98F00B204E9800998ECF8427E
[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Info   :     R2API] Server Handlers registered
[Warning: Unity Log] The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
[Info   :     R2API] Client Handlers registered
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] FlashWindow.Flash(791966)
[Info   : Unity Log] Active scene changed from  to lobby
[Info   : Unity Log] Loaded scene lobby loadSceneMode=Single
[Info   : Unity Log] gridColumns=8,totalElements=10,gridRows=2,maxEntryCount=16
[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] GameNetworkManager.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:251 pos:251
[Info   : Unity Log] FlashWindow.Flash(791966)
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby currentSceneName=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "C:\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for Clef the Mouse
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from Clef the Mouse
[Info   : Unity Log] Accepting vote from Clef the Mouse
[Info   : Unity Log] <style=cEvent>Clef the Mouse connected.</color>
[Info   : Unity Log] Unloaded scene lobby
[Info   : Unity Log] Active scene changed from  to golemplains2
[Info   : Unity Log] Loaded scene golemplains2 loadSceneMode=Single
[Info   : Unity Log] OnClientSceneChanged networkSceneName=golemplains2 currentSceneName=golemplains2
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Spending 220 credits on interactables...
[Info   : Unity Log] reorder list
[Info   : Unity Log] <style=cEvent>You picked up <color=#FFFFFF>Lens-Maker's Glasses</color></color>
[Info   : Unity Log] <style=cEvent>You picked up <color=#E7543A>57 Leaf Clover</color></color>
[Info   : Unity Log] Chatbox showInput:True
[Info   : Unity Log] Chatbox showInput:False
[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!
[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=None }
[Info   : Unity Log] Network shutting down...
[Info   : Unity Log] Server shutting down...
[Info   : Unity Log] Issued kick message to all remote clients.
[Info   : Unity Log] Finished waiting for clients to disconnect.
[Info   : Unity Log] StopHost()
[Info   : Unity Log] Server shutdown complete.
[Info   : Unity Log] Unloaded scene golemplains2
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] Saved file "1d6065f6-d82c-4902-a851-e4222b5d7c81.xml" (148570 bytes)
[Info   : Unity Log] Shutting down Steamworks...
[Info   : Unity Log] Shut down Steamworks.
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.ItemIcon.SetItemIndex
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.EquipmentIcon.Update
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.GenericNotification.SetItem
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.GenericNotification.SetEquipment
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.SetPickupOptions
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.Awake
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.PickupPickerPanel.OnCreateButton
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.GlobalEventManager.ClientDamageNotified
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.ItemInventoryDisplay.OnInventoryChanged
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.BuffIcon.Awake
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.BuffIcon.UpdateIcon
[Debug  :     R2API] Hook removed by assembly: BetterUI.dll for: RoR2.UI.HUD.Awake
`

**Comment by xoxfaby** [comment]
yes, also it's \`\`\` for longer codeblocks (i've gone and fixed it for you). I will probably change the default bug template to include instructions to upload a log as a [gist](https://gist.github.com/) instead of listing mods.

**Comment by RandomNerd1** [comment]
Gotcha, thanks for looking into it! 👍
