### ISSUE TITLE
Repulsion Plate lists wrong stat (localization?)

### ISSUE THREAD

**Issue by MissPotato** [xoxfaby/BetterUI#163]
*If you submit an incomplete bug report that doesn't follow this template completely, it will be closed without reading until you update the bug report with the missing info*

**Describe the bug**  
Repulsion Armor plate reduces incoming damage by a flat 5 damage, however the tooltip states it is armor, which reduces a % of damage. 

**Link your log file**  
https://pastebin.com/JgFn2agz

**Does the error occur when only using BetterUI and no other mods?**  
Only BepinEx and BetterUI are installed

**BetterUI Version**  
Which version of BetterUI you're using e.g.: v2.7.6

**Additional information**  
I do have the DLC if that might cause issues

**Comment by xoxfaby** [comment]
You are right, not sure where this incorrect info came from, will be fixed soon.
