### ISSUE TITLE
proc coefficient 

### ISSUE THREAD

**Issue by Hammerkirby123** [xoxfaby/BetterUI#169]
Could you have an updated proc coefficient check in case some items change the proc coefficient and might have different chances>

**Comment by xoxfaby** [comment]
There is no way to check the proc coefficient, if a mod changes them, they need to modify the value in BetterUI

**Comment by xoxfaby** [comment]
As a clarification, it is technically possible to write code to check all of the proc coefficients at runtime but it would be an incredibly involved system that is uniquely written for every skill and I have no plans to ever add that to BetterUI
