### ISSUE TITLE
Command menu is breaking and everything is becoming chronobauble.

### ISSUE THREAD

**Issue by g0shu** [xoxfaby/BetterUI#17]
**Describe the bug**
[This is the log file](https://gist.github.com/g0shu/1d180353fac59c662d90c084c4a653b2), look at the very end of it. I have not been able to replicate this intentionally with or without other mods installed, but it happened a few times when going to the artifact realm after sky meadow (I don't play with command on permanently so can't speak for that).
Artifact key:
![](https://i.imgur.com/n51YDx3.png)
White item:
![](https://i.imgur.com/i3rcQIs.png)
**What other mods do you use**
See log file.

**BetterUI Version**
1.4.4

**Additional information**
Hovering chronobaubles will show item tooltips and clicking one of them will spawn that item, unfortunately doesn't work for artifact keys, thus killing the run.

**Comment by xoxfaby** [comment]
Very weird stuff. Please do let me know if you can recreate this reliably or have any other clues. I suggest installed ProperSave so you can recover runs like this by restarting.

**Comment by g0shu** [comment]
Made a fresh profile, installed nothing but betterui (hate playing without EmptyChestsBegone ugh), and copied over my config files from the main profile. Got chronobaubles again. 
[New log](https://gist.github.com/g0shu/d0fa1f0ae9ea6ba2f37cb061f035f56f) and zipped up [configs](https://github.com/xoxfaby/BetterUI/files/5252037/config.zip) if you want to take a look. Maybe they're the issue.

**Comment by g0shu** [comment]
Here's something potentially interesting? Got chronobaubles again, backed out to the main menu and loaded the save - they appeared every time after a few attempts. [Log](https://gist.github.com/g0shu/1a6dfc2c28e0c088b83f1f39e5b40cea).
However, after restarting the game and loading that same save they were gone. After that tried backing out to the menu restarting the game a few more times but they never returned.

**Comment by xoxfaby** [comment]
what timing, haha, I was just looking at this. I just figured out what's happening. This bug is because of an oversight from me when I moved part of the code for the buttons. This makes a lot of sense suddenly and should be an easy fix.

**Comment by xoxfaby** [comment]
I'm gonna take a wild guess and say this only started happening for you any time you used a scrapper :p

**Comment by g0shu** [comment]
Oh maybe? That'd explain why i couldn't get it to happen when rushing there using cheats.
