### ISSUE TITLE
[Suggestion] Display item's mod source and internal name.

### ISSUE THREAD

**Issue by Darkmega18** [xoxfaby/BetterUI#171]
Would it be possible when looking at items and their descriptions to show maybe in gray text at the bottom of the item what mod it's from and what it's internal name is etc? it could be useful for configuring mods and discovering whats from where in large modpacks and configuring things accordingly for those with not so great moment to moment memory. (it'll certainly save me a few google searches etc)

Similar to how minecraft in extended tooltips mode (and probably contributed too by other mods I have, but I'm not even sure anymore cause I don't do pure vanilla ever) will display an items name at the bottom of it's tooltip box.
![image](https://github.com/xoxfaby/BetterUI/assets/8104689/9dfba0d3-54cf-4031-8a01-147024cfb80c)
notice the items attribute descriptions etc, but down the bottom in grey it has the items actual item name which can be used in configs and such. something like this basically.

**Comment by xoxfaby** [comment]
https://thunderstore.io/package/Bubbet/WhatAmILookingAt/

**Comment by Darkmega18** [comment]
owo. welp. I guess so.
