### ISSUE TITLE
dps meter and all the stats wont show up

### ISSUE THREAD

**Issue by grabthebait** [xoxfaby/BetterUI#172]
Describtion:
BetterUI shows everything except the DPS-meter and the item stats one the top right side right under the wave window

log file:
[log.txt](https://github.com/xoxfaby/BetterUI/files/12062784/log.txt)

Does the error occur when only using BetterUI and no other mods?
yes

BetterUI Version:
2.7.9

Additional Information:
this bug/error shows up sometimes after i start the game normally. after a few weeks or so its gone but it may come back in the same day

**Comment by xoxfaby** [comment]
Please reopen with a log file, that is not a log file

**Comment by grabthebait** [comment]
all good i guess
i fixed it by myself because i created a new profile with the same mods and it worked!
im very sry to disturb you with that but tyvm for the quick answer ^^

**Comment by grabthebait** [comment]
:)
