### ISSUE TITLE
Proc coeff errors/omissions in 1.5.0?

### ISSUE THREAD

**Issue by RandomNerd1** [xoxfaby/BetterUI#18]
**Describe the bug**
Some of the proc coefficients seem to be incorrect in the mouseover display in-game:

Huntress
-Arrow Rain: Wiki says 0.2, mod displays no proc coeff

MUL-T
-TR58 Carbonizer Turret: Wiki says 0.6, mod displays 0.55 (did you get this value from code-diving? Seems too specific to actually be a mistake)

Artificer
-Cast Nano-Spear: Wiki says 1, mod displays no proc coeff

REX
-Seed Barrage: Wiki says 0.5, mod displays 1

Loader
-Grapple Fist: Has no proc coeff, mod displays 1

Captain
-Vulcan Shotgun: Wiki says 0.75, mod displays 1
-Orbital Supply Beacon: Wiki says 0, mod displays no proc coeff (more nitpicky, but since dropping the beacon itself does do 2000% damage, it's more correct to show the proc coeff of 0, rather than displaying nothing at all, which is more appropriate for skills that don't affect enemies at all)

**What other mods do you use**
Same as last time, lol

**BetterUI Version**
1.5.0

**Additional information**

**Comment by xoxfaby** [comment]
Which wiki are you going by?

**Comment by RandomNerd1** [comment]
https://riskofrain2.gamepedia.com

**Comment by g0shu** [comment]
For engi turrets, wiki actually gives 2 different values ¯\_(ツ)_/¯
https://riskofrain2.gamepedia.com/Proc_Coefficient#Engineer
https://riskofrain2.gamepedia.com/Engineer#TR58_Carbonizer_Turret

**Comment by RandomNerd1** [comment]
> For engi turrets, wiki actually gives 2 different values ¯\_(ツ)_/¯
> https://riskofrain2.gamepedia.com/Proc_Coefficient#Engineer
> https://riskofrain2.gamepedia.com/Engineer#TR58_Carbonizer_Turret

lol, google comes up with only the proc coeff page having the 0.55, but comes up with multiple results for 0.6, I'd guess 0.6 is right, but I have to wonder where the more specific figure came from, and if it's correct lol

**Comment by xoxfaby** [comment]
Yeah that wiki is where I got my values from and it agrees with what I'm seeing. 

It does look like I missed the Huntress Arrow Rain and the Captain Shotgun was a mistake. Seed Barrage is a 1 in the wiki. Artificer Spear missing was probably a copy paste mishap . I will correct the incorrect values in a bit unless you feel like making a pull request before then. 

If you end up going code diving to confirm the Laser turret ( and to confirm the Captain's supply drop and `CallSupplyDropShocking` ( which I made a guess at that it would be 1 ), do let me know.

**Comment by RandomNerd1** [comment]
Yeah, I confused seed barrage and directive drill, that was my mistake.

And I don't know how to code dive, so :D And no rush for me, I can wait for next version to hit thunderstore.

Just asked about the 0.55 vs. 0.6 in the discord, waiting on an answer for that.

**Comment by xoxfaby** [comment]
alright thanks, I'll update it soon. Unless you can figure it out I will keep it at 0.55 probably. 

Also holy shit how did you even find all these discrepancies so fast? haha

**Comment by xoxfaby** [comment]
Alright, I misread that, I thought it changed based on the attack speed of the turret ( including ) items, but actually it's just the base proc coefficient ( 3 ) divided by the base fire frequence ( 5 ) so 3/5 which is 0.6. Solved.
