### ISSUE TITLE
Missing localization string for Fuel Array

### ISSUE THREAD

**Issue by SlawekNowy** [xoxfaby/BetterUI#182]
**Describe the bug**  
There's no Localization string for Fuel Array if PickupDescriptionAdvanced is true.

[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/14144693/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**  

**BetterUI Version**  
Which version of BetterUI you're using e.g.: v2.8.4

![20240202204235_1](https://github.com/xoxfaby/BetterUI/assets/38943477/dfb1c2e3-bb8e-4680-83f4-c36bde51008f)

**Comment by SlawekNowy** [comment]
Found two more cases: wrong localization string on Broken watch and missing localization for empty flask.

**Comment by xoxfaby** [comment]
These are not really BetterUI issues, these are just things missing from the logbook. At this point I don't think I'll be doing anything to fix this unless we went through an effort and correct all bad in-game strings.
