### ISSUE TITLE
Latest version breaks my game

### ISSUE THREAD

**Issue by caspaas** [xoxfaby/BetterUI#186]
**Describe the bug**  
Latest Version suddenly broke my game
and when i disable it it works again.

**Link your log file**  
https://easyupload.io/1x532c

**Does the error occur when only using BetterUI and no other mods?**  
No, only with other mods
And it only occurs on loading/starting the game
Then it just breaks and has infinite loading.

**BetterUI Version**  
2.8.9

**Comment by xoxfaby** [comment]
> [Error  :   BepInEx] Could not load [MysticsRisky2Utils 2.0.16] because it is incompatible with: com.xoxfaby.BetterUI

 This is probably an issue with one of mystics mods

**Comment by caspaas** [comment]
oh my bad, do i need to write in their github too ?
for now i reverted back to an older BetterUI version

**Comment by xoxfaby** [comment]
Probably the way to go as it's not a BetterUI issue

**Comment by caspaas** [comment]
Done! and thank you ^^ 
sorry tho
