### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by GadgetLaboratory** [xoxfaby/BetterUI#189]
Thanks for completely ruining the mod and the experience for literally every single person who uses your Better UI, including every other person who has literally nothing to do with all the nonsense that's been going down, me being one of them.
I hope you've realized that your nuclear response has not only made the issue worse, but also ensured you will be getting a hell of a lot more backlash that you already were.  Congratulations.  A lot more people will be voicing their grievances towards you, in a lot more means than just here.  Good luck escaping from all of it, and I hope you have the day you deserve.

**Comment by xoxfaby** [comment]
Imagine not realizing you're exactly the kind of person who is the reason I'm doing this. You did this to yourself.
