### ISSUE TITLE
Archive The Repo

### ISSUE THREAD

**Issue by WhoNeedsAUsrName** [xoxfaby/BetterUI#191]
**What feature would you like added to BetterUI?**
Archive the repo, if the mod is dead, archive the repo to further minimise confusion
and bug reports/prs, mostly those

**Comment by th3d00d** [comment]
Are there any alternatives to BetterUI? just wanted to play some RoR2 after a while of not playing and saw the mod was deprecated :/

**Comment by Deadoon** [comment]
> Are there any alternatives to BetterUI? just wanted to play some RoR2 after a while of not playing and saw the mod was deprecated :/

[LookingGlass](https://thunderstore.io/package/DropPod/LookingGlass/)

**Comment by xoxfaby** [comment]
I've not decided yet what I'm doing with the mod and it's currently available on the discord. I'm not archiving the repo at this time.

**Comment by Deadoon** [comment]
> Are there any alternatives to BetterUI? just wanted to play some RoR2 after a while of not playing and saw the mod was deprecated :/

[Looking glass](https://thunderstore.io/package/DropPod/LookingGlass/) @th3d00d It was deleted to hide competition.

**Comment by xoxfaby** [comment]
yes, I'm hiding the links for mods made by the people who have harrassed me and are the reason I left ror2 modding.
