### ISSUE TITLE
Why Change The Mod to Only The Button?

### ISSUE THREAD

**Issue by Jarthuzad** [xoxfaby/BetterUI#195]
I understand wanting to deprecate the mod, the ROR modding community is weirdly toxic, but this is one of my favorite mods for the game, The QoL additions make the game add so much and to remove all of it but the menu button seems odd to me, I would just leave the circles and let the mod sit as is, as over 2.5 MILLION people have downloaded this mod, its a staple of the game and the removal of it hurts. Most people are normal, and all this does is hurt each and every one of them while appeasing the assholes you took it down for in the first place. I guarantee you no more than 5000 of that 2.5 million (roughly 0.002%) give a shit about menu buttons or whatever is was exactly that they are mad about. I love this mod, from having sorted items, seeings my raw stats in numbers, and being the best extended item description mod, I really don't wanna see it go, at least leave it as is or let others take the mantle that you know/trust.

I know you said the decision is final (and I'm a month late), but I just want to be able to use this mod again, there is a reason it is the mod downloaded mod, more than Enforcer, more than fuckin' Starstorm 2, hell even more than HookGenPatcher (which as im sure you know is a library for thousands of mods)

If you still decide to leave it as is, I'm sorry for wasting your time and for all the shit you got either way, I just don't think this is the right choice and I want to express that (and don't want to join a discord just to do this, it feels wrong).

**Comment by xoxfaby** [comment]
This is not the place to discuss this, if you want to discuss this, yes, discord is the right place
