### ISSUE TITLE
Only show UI while holding the TAB key

### ISSUE THREAD

**Issue by freefall9027** [xoxfaby/BetterUI#21]
**What feature would you like added to BetterUI?**
Is there a way to display betterUI ONLY while holding the TAB key? I am a huge fan of the mod, I just personally like to have my screen less cluttered all the time.

Thank you

**Comment by xoxfaby** [comment]
Which part of BetterUI?

**Comment by freefall9027** [comment]
The stats part (the info on the right), similar to how the portal true/false info slides in and out when you hold the TAB key, but for all the stats.

**Comment by xoxfaby** [comment]
This is already part of the mod

**Comment by freefall9027** [comment]
You're totally right! I'm new to ROR2 mods and didn't know about config files, but I found them and changed them to my liking.

Is there any way there can be a toggle key for the stats to show or hide without bringing up the scoreboard (holding the TAB key)? That way I can quickly show/hide the stats and still turn around with the mouse. I know this is super extra and probably only for me, but I would greatly appreciate it.

**Comment by xoxfaby** [comment]
Sure, I will implement this in the next update with a custom bind I suppose.
