### ISSUE TITLE
Show difficulty coefficient by StatsDisplay

### ISSUE THREAD

**Issue by emtkmkk** [xoxfaby/BetterUI#22]
**What feature would you like added to BetterUI?**

- It would be useful and helpful if StatsDisplay could show the difficulty coefficient used for scaling, such as the cost of chests.

**Comment by xoxfaby** [comment]
I'll have to look into this but I expect it to be very easy so you will likely see this in the next update.

**Comment by vrnvorona** [comment]
Kinda necroposting, but maybe some sort of UI to show current stage chest prices as-is? I know the math behind prices, but it could be convenient to just know price of legendary instead of multiplying current small chest by 16 while actively not dying.
