### ISSUE TITLE
$luckcrit is broken

### ISSUE THREAD

**Issue by g0shu** [xoxfaby/BetterUI#23]
**Describe the bug**
9 glasses 0 clovers:
![](https://i.imgur.com/frYnris.png)
10 glasses 0 clovers:
![](https://i.imgur.com/B9tKMDA.png)
1 glasses 10 clover:
![](https://i.imgur.com/lqR8NOB.png)

**What other mods do you use**
betterui and cheats for testing

**BetterUI Version**
1.5.6

**Comment by xoxfaby** [comment]
Oh this is probably an artifact from when I redid the LuckCalc in conjunction with changing the ProcItemsCatalog. Will be an easy fix, thank you for reporting.
