### ISSUE TITLE
Show cooldowns on skills

### ISSUE THREAD

**Issue by freefall9027** [xoxfaby/BetterUI#25]
**What feature would you like added to BetterUI?**
Is there a way you can add the base cooldown and effective cooldown for skills in the same place the proc info is shown (similar to what it shows for equipment/active item)? Maybe even a countdown timer as well.

**Comment by xoxfaby** [comment]
I mean there is a countdown timer on skills when you us them??

But I can *probably* add this extra info, sure.

**Comment by freefall9027** [comment]
Sorry for bothering so much! I just like to see the exact effect that alien head or purity have on skills

**Comment by xoxfaby** [comment]
No problem, I'm just confused what you mean by 

>Maybe even a countdown timer as well.

**Comment by freefall9027** [comment]
similar to the buff/debuff countdown timer

**Comment by xoxfaby** [comment]
But this is already in the base game? There is a big number on the skill when it's on cooldown?

**Comment by freefall9027** [comment]
Yeah but it's not as precise as decimal. I do agree though that it's probably not needed.
