### ISSUE TITLE
[ItemCounters] Fallback option for missing items

### ISSUE THREAD

**Issue by MightyW0lf** [xoxfaby/BetterUI#27]
If the item is not in the configuration, use its tier's score for the total score instead. (such items have currently 0 score)

**Comment by xoxfaby** [comment]
They shouldn't, currently items that are missing are added to the configuration file with a score based on their tier.

**Comment by MightyW0lf** [comment]
Oh, then consider it a bug report, since I don't have items from the ChensClassicItems mod in the configuration file.

**Comment by xoxfaby** [comment]
I can't reproduce this, did you maybe forget to launch the game before trying to edit the config?

**Comment by xoxfaby** [comment]
> (such items have currently 0 score) 

did you even confirm that this is what happens?

**Comment by MightyW0lf** [comment]
I can send you more info-

Here's a screenshot with 0 score and Dead Man's Foot in my inventory. My Tier2 score is configured to 25. Dead Man's Foot's score can't be configured.
![](https://i.imgur.com/jYMqaaQ.png)

Then with Razorwire, I have 15 score. (to demonstrate the score for a vanilla item works as intended - my Razorwire score is configured to 15)
![](https://i.imgur.com/jswQgfX.png)

Another screenshot with another item from the ChensClassicItems mod added, but the score stays the same (my Tier3 score is configured to 100).
![](https://i.imgur.com/d646Z7V.png)

Items from other mods which are in the configuration (AFAIK only items from the ChensClassicItems mod are missing) work fine as expected. (score Hardened Bone Fragments is configured to 15)
![](https://i.imgur.com/U0n0h65.png)

I thought maybe some of the more "technical" names (such as `ITEM_MAGEATTUNEMENT_NAME`) could be the items from the ChensClassicItems mod, but I tried changing the score for all of them and was still getting 0 for the items from that mod.

**Comment by xoxfaby** [comment]
What is your `ItemScoreFromTier` set to?

>I thought maybe some of the more "technical" names (such as ITEM_MAGEATTUNEMENT_NAME) could be the items from the ChensClassicItems mod

Each config setting has the in-game name as the description, and the ItemIndex as the key, , if you want to change the Dead Man's Foot, simply search for it ![Deadmansfoot](https://fby.pw/eLuh.png)

**Comment by MightyW0lf** [comment]
Okay, now it's in the configuration and I feel stupid. But yesterday (~16hrs ago) it wasn't there (and yes, I launched the game with the mod to let its configuration generate):
![](https://i.imgur.com/ZGN0vVV.png)

But here's something interesting - the IDs of all items with numeric IDs shifted and **the score didn't shift with them**.

Hardened Bone Fragments went (for some unknown reason) to the bottom of the list and caused a shift by 1:
*(ignore the items with IDs `138` and `139` as I manually edited them between those 2 versions)*
![](https://i.imgur.com/m8WfGui.png)

And then the items from the ChensClassicItems mod appeared and caused shift by another 3 items:
![](https://i.imgur.com/VofmueU.png)

I assume the numeric IDs are generated and you can't ensure they'll stay always the same, but the score not changing with them is quite an annoying bug.

Anyway setting score for the items from the ChensClassicItems mod works now, really sorry about that.

**Comment by xoxfaby** [comment]
I might be able to change it to be based on the language token but ideally ClassicItems would register themselves in a way that gives them a fixed item index name. I need to look into if that's their fault or a shortcoming of R2API's ItemAPI

**Comment by MightyW0lf** [comment]
I think it's more likely to be a shortcoming of R2API's ItemAPI as none of the modded items have a fixed item index name (aside from the LunarWickedRing mod with `CooldownOnCrit`, but I assume that is already included in vanilla, because I don't have that mod installed and still have the item name in the configuration).
