### ISSUE TITLE
[ItemCounters] ItemScores as a single configuration field with a map

### ISSUE THREAD

**Issue by MightyW0lf** [xoxfaby/BetterUI#28]
Instead of creating a field for every item (which requires frequent updates to keep the list up to date with the latest mods), replace it with a single field with a map, where key would be the ID of the item and value would be its score separated by columns or whatever (e.g. `HealOnCrit=35,Phasing=25,Clover=150`). This way, users can add the missing items and only the default configuration would need to be updated. Link to a list of item IDs could be in the field description for convenience.

**Comment by xoxfaby** [comment]
I don't see how this would be an improvement

**Comment by MightyW0lf** [comment]
I assumed you're adding the items to the cofniguration manually. If not, then this wouldn't make sense to do.

**Comment by xoxfaby** [comment]
The mod automatically takes all items from the ItemCatalog
