### ISSUE TITLE
An option to have an item description appear on Lunar items before pickup.

### ISSUE THREAD

**Issue by orare** [xoxfaby/BetterUI#29]
I always have a hard time remembering what lunar items do so being able to see the item description before picking them up would be very handy.

**Comment by xoxfaby** [comment]
hmm, this is a good idea, I wonder where it should be displayed though

**Comment by g0shu** [comment]
you can just ping the item and it'll show you the description

**Comment by xoxfaby** [comment]
I think I found a very good solution for it

![](https://fby.pw/xMKL.png)
