### ISSUE TITLE
[Suggestion] Scrapper Command

### ISSUE THREAD

**Issue by EmuLegs** [xoxfaby/BetterUI#3]
Love the mod it's very nice indeed.
Could you add a way to sort the menus of the Scrapper and Command Artefact?

(or even just match the item order the player selected?)

**Comment by xoxfaby** [comment]
Interesting, I had not considered this, I will need to look into how these are generated to see if it's possible. I will get back to you.

**Comment by EmuLegs** [comment]
Thank you that would be great 😄

**Comment by xoxfaby** [comment]
https://fby.pw/k8S3.png

Right now I'm trying to decide how to handle command. I think I will put it on a separate toggle and give each a custom sorting algorithm. I think people will want the command window to be alphabetical or by stacks, which might not be the same as they want from others.

**Comment by EmuLegs** [comment]
Sorry to make this hard, but I would Love it sorted by stack with the last selected item in the middle (under the mouse spawn) ❤️

**Comment by xoxfaby** [comment]
In the command menu? I'm not sure if this could be feasibly implemented. It would have to sort them from the middle out essentially?

**Comment by xoxfaby** [comment]
or are you saying just last item int he middle and the rest sorted as normal?

**Comment by EmuLegs** [comment]
Just the last item so you can reselect it with out moving the mouse

**Comment by xoxfaby** [comment]
Hmm, that seems reasonable ( and doable, just have to move it to the right index ).
