### ISSUE TITLE
Using Japanese in the username will cause some information to not be displayed.

### ISSUE THREAD

**Issue by emtkmkk** [xoxfaby/BetterUI#30]
**Describe the bug**
If you use Japanese characters in your user name, the amount of money you have will disappear from the scoreboard.

**What other mods do you use**
bbepis-BepInExPack-5.3.1
tristanmcpherson-R2API-2.5.14
JohnEdwa-RTAutoSprintEx-1.1.2
TheRealElysium-EmptyChestsBeGone-1.1.1
Pickleses-TeleporterShow-2.3.2
MagnusMagnuson-ScannerPlusOne-2.6.1
frostycpu-UnmoddedVersion-1.0.1
wildbook-MiniRpcLib-0.0.2
Jarlyk-Raincoat-1.0.5
ontrigger-ItemStatsMod-2.0.0
kinggrinyov-AutoSkipIntroCutscene-1.0.1
Harb-LighterPatcher-1.0.4

**BetterUI Version**
v1.6.2

**Additional information**
I think this is probably because Japanese characters have a problem with the font size specification not being properly reflected.

**Comment by emtkmkk** [comment]
![image](https://user-images.githubusercontent.com/65014664/94337112-f0933780-0022-11eb-88d2-1f3f6e651291.png)

**Comment by xoxfaby** [comment]
Hmm this is interesting, I'm not sure how to best handle this, can you try this test build?

https://fby.pw/BetterUI.dll

**Comment by emtkmkk** [comment]
From the looks of things, I don't think they've been fixed…

**Comment by xoxfaby** [comment]
Can you give a screenshot of what it looks like?

**Comment by emtkmkk** [comment]
There are no changes from the previous screenshot...
