### ISSUE TITLE
Equipment Cooldowns no longer show up as of BetterUI 1.6.8 and higher

### ISSUE THREAD

**Issue by Sasurai087** [xoxfaby/BetterUI#37]
**Describe the bug**
BetterUI no longer shows cooldown stats on equipment when using versions beyond 1.6.7.

**Link your log file**
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/5373926/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**
Tested with only BepinExPack, R2API, and BetterUI. I made sure to delete and initialize all my config files each time I tested.

**BetterUI Version**
Issue observed on BetterUI versions 1.6.8, 1.6.9, and 1.6.10. I was using 1.6.10 on the attached LogOutput.

**Additional information**
I first noticed issue on October 11, 2020. I was running 70 mods at the time. Isolated the cause of issue to BetterUI versions 1.6.8 and above. As a final test, I went back to my original profile with 70 mods, but swapped out BetterUI 1.6.10 with 1.6.7 and equipment cooldowns were displaying again.

P.S. Thank you so much for making this mod! It's one of my absolute favorites and one I make sure all my friends have.

**Comment by Sasurai087** [comment]
Hello! Thank you for looking into this. The issue still seems to be present as of 1.6.11 and 1.6.12. Just in case I'm missing something, I want to clarify that I was expecting to see cooldown and effective cooldown stats (with Fuel Cell) on equipment when holding TAB to open the scoreboard, then hovering my cursor at the equipment on the lower right of the screen. This feature appears to be missing as of 1.6.8 and above.

I tested with the same conditions as before: BetterUI (and dependencies) is the only enabled mod, reinitialized configs. Log was taken from a test run using BetterUI 1.6.12.
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/5380514/LogOutput.log)

I appreciate your help on this and please let me know if there's any more information I can provide.

**Comment by itsPoipoi** [comment]
Same things Sasurai said.
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/5385509/LogOutput.log)

**Comment by xoxfaby** [comment]
this time fixed for real lol
