### ISSUE TITLE
Reminders for anniversary update

### ISSUE THREAD

**Issue by breadguy69** [xoxfaby/BetterUI#47]
- cooldown tooltip check on lobby create
- update proc coefs for any changes, new skills, bandit
- stats display toggle button

**Comment by xoxfaby** [comment]
- [ ] Reload cooldown tooltip if changed by other mods
- [x] Update proc coefficients for new items ( No new ones? )
- [x] Update proc coefficients for new character skills
- [x] Update proc coefficients for new lunar skills 
- [ ] Add StatsDisplay toggle option
