### ISSUE TITLE
It just.. Doesn't work

### ISSUE THREAD

**Issue by ArcaneBowser** [xoxfaby/BetterUI#49]
Been about 2 months since I've played ROR2 and used mods, so maybe I'm just forgetting something.
The item stats are displayed in the logbook, but when I get into a game the mod ceases to do anything
I even tried using it with the original ItemStats and still nothing

**Comment by xoxfaby** [comment]
Can you try using the r2 mod manager?

**Comment by xoxfaby** [comment]
If you don't want to do that, please make sure you have Bepinex installed.
