### ISSUE TITLE
Change MMHook Mod

### ISSUE THREAD

**Issue by NutNutty64** [xoxfaby/BetterUI#51]
It seems clear now that [HookGenPatcher](https://thunderstore.io/package/RiskofThunder/HookGenPatcher/) by RiskofThunder is the definitive mod for loading the MMHook assembly (R2API itself requires it now), and I suggest switching over to it to avoid issues and to make it so that people using the r2modman don't have two mods for loading the assembly.

**Comment by xoxfaby** [comment]
Nope, not untill it doesn't require R2API
