### ISSUE TITLE
Unable to select items when using Artifact of Command

### ISSUE THREAD

**Issue by 07y678** [xoxfaby/BetterUI#52]
**Describe the bug**
When using Artifact of Command, the item selection screen is blank

**Link your log file**
﻿[Message:   BepInEx] BepInEx 5.4.9.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.Loader 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [MMHookDummyMod 1.0.2]
[Info   :   BepInEx] Loading [BetterUI 2.0.2.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   : Unity Log] Facepunch.Steamworks Unity: WindowsPlayer

[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   : Unity Log] Facepunch.Steamworks Os: Windows

[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] Facepunch.Steamworks Arch: x64

[Info   :   Console] Searching for compatible XInput library...
[Info   : Unity Log] Searching for compatible XInput library...

[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] Found Xinput1_4.dll.

[Info   : Unity Log] Initializing Mod System...
[Info   : Unity Log] Mod System initialized.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Setting current language to "zh-CN"
[Info   : Unity Log] Could not load files for language "zh-CN". Falling back to "en".
[Info   : Unity Log] Launch Parameters: 
  arg[0]="D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
  arg[1]="--doorstop-enable"
  arg[2]="true"
  arg[3]="--doorstop-target"
  arg[4]="C:\Users\wcnnn\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\core\BepInEx.Preloader.dll"

[Info   : Unity Log] Setting current language to "zh-CN"
[Info   : Unity Log] Could not load files for language "zh-CN". Falling back to "en".
[Info   : Unity Log] Loaded archived convars.
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"
[Info   : Unity Log] LoadContentPacks() start
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
BetterUI.CommandImprovements.Start () (at <d2fb79a5cdd844a49d46281e14f8da08>:0)
BetterUI.BetterUI.Start () (at <d2fb79a5cdd844a49d46281e14f8da08>:0)

[Info   : Unity Log] LoadContentPacks() end
[Info   : Unity Log] Game content load completed in 4201ms.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.ReturnToBase (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.TravelToEnd (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.WaitAtTop (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.Language] Setting current language to "zh-CN"
[Info   : Unity Log] Attempting to load user profile /UserProfiles/417deb81-8d9c-4e89-859a-94aea16112dc.xml
[Info   : Unity Log] stream.Length=114496
[Info   : Unity Log] Attempting to load user profile /UserProfiles/cec13d45-9f48-4860-9b46-b06a4203effc.xml
[Info   : Unity Log] stream.Length=141508
[Info   : Unity Log] Unloaded scene loadingbasic
[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to intro
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to intro
[Info   : Unity Log] Loaded scene intro loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene intro
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Info   : Unity Log] Loaded scene lobby loadSceneMode=Single
[Info   : Unity Log] gridColumns=8,totalElements=11,gridRows=2,maxEntryCount=16
[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] GameNetworkManager.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:251 pos:251
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby currentSceneName=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for zerg
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from zerg
[Info   : Unity Log] Accepting vote from zerg
[Info   : Unity Log] <style=cEvent>zerg已连接。</color>
[Info   : Unity Log] NetworkUser(Clone) (RoR2.NetworkUser)
[Info   : Unity Log] maxRuleCount=2, currentChoiceIndex=1
[Info   : Unity Log] NetworkUser(Clone) (RoR2.NetworkUser)
[Info   : Unity Log] maxRuleCount=2, currentChoiceIndex=1
[Info   : Unity Log] NetworkUser(Clone) (RoR2.NetworkUser)
[Info   : Unity Log] maxRuleCount=2, currentChoiceIndex=1
[Info   : Unity Log] Unloaded scene lobby
[Info   : Unity Log] Active scene changed from  to blackbeach
[Info   : Unity Log] Loaded scene blackbeach loadSceneMode=Single
[Info   : Unity Log] OnClientSceneChanged networkSceneName=blackbeach currentSceneName=blackbeach
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Spending 180 credits on interactables...
[Info   : Unity Log] reorder list
[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from WispBody(Clone) (RoR2.CharacterBody): 5
[Warning: Unity Log] Animator.GotoState: State could not be found
[Warning: Unity Log] Invalid Layer Index '-1'
[Info   : Unity Log] Drop chance from WispBody(Clone) (RoR2.CharacterBody): 5
[Warning: Unity Log] Animator.GotoState: State could not be found
[Warning: Unity Log] Invalid Layer Index '-1'
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from GolemBody(Clone) (RoR2.CharacterBody): 11.60964
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from GolemBody(Clone) (RoR2.CharacterBody): 11.60964
[Info   : Unity Log] Drop chance from BeetleBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from LemurianBody(Clone) (RoR2.CharacterBody): 5
[Info   : Unity Log] Drop chance from GolemBody(Clone) (RoR2.CharacterBody): 11.60964
[Info   : Unity Log] Drop chance from GolemBody(Clone) (RoR2.CharacterBody): 11.60964
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
BetterUI.CommandImprovements.PickupPickerPanel_SetPickupOptions (On.RoR2.UI.PickupPickerPanel+orig_SetPickupOptions orig, RoR2.UI.PickupPickerPanel self, RoR2.PickupPickerController+Option[] options) (at <d2fb79a5cdd844a49d46281e14f8da08>:0)
DMD<>?408785408.Hook<RoR2.UI.PickupPickerPanel::SetPickupOptions>?-538733568 (RoR2.UI.PickupPickerPanel , RoR2.PickupPickerController+Option[] ) (at <ac79f8742d8b40d3bba8a4d9098cc62b>:0)
RoR2.PickupPickerController.OnDisplayBegin (RoR2.NetworkUIPromptController networkUIPromptController, RoR2.LocalUser localUser, RoR2.CameraRigController cameraRigController) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.set_currentCamera (RoR2.CameraRigController value) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.OnControlBegin () (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.set_inControl (System.Boolean value) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.UpdateBestControllerForLocalUser (RoR2.LocalUser localUser) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.OnLocalParticipantDiscovered (RoR2.LocalUser localUser) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.set_currentLocalParticipant (RoR2.LocalUser value) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.OnParticipantDiscovered (RoR2.CharacterMaster master) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.set_currentParticipantMaster (RoR2.CharacterMaster value) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.SetParticipantMasterId (UnityEngine.Networking.NetworkInstanceId newMasterObjectInstanceId) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.set_NetworkmasterObjectInstanceId (UnityEngine.Networking.NetworkInstanceId value) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.SetParticipantMasterId (UnityEngine.Networking.NetworkInstanceId newMasterObjectInstanceId) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.SetParticipantMaster (RoR2.CharacterMaster newParticipantMaster) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.NetworkUIPromptController.SetParticipantMasterFromInteractor (RoR2.Interactor newParticipantInteractor) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.PickupPickerController.OnInteractionBegin (RoR2.Interactor activator) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.Interactor.PerformInteraction (UnityEngine.GameObject interactableObject) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.Interactor.AttemptInteraction (UnityEngine.GameObject interactableObject) (at <6e882c67227c45d48048fa96336d8982>:0)
RoR2.InteractionDriver.FixedUpdate () (at <6e882c67227c45d48048fa96336d8982>:0)

[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=None }
[Info   : Unity Log] Network shutting down...
[Info   : Unity Log] Server shutting down...
[Info   : Unity Log] Issued kick message to all remote clients.
[Info   : Unity Log] Finished waiting for clients to disconnect.
[Info   : Unity Log] StopHost()
[Info   : Unity Log] Server shutdown complete.
[Info   : Unity Log] Unloaded scene blackbeach
[Info   : Unity Log] Active scene changed from  to title
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Info   : Unity Log] Loaded scene lobby loadSceneMode=Single
[Info   : Unity Log] gridColumns=8,totalElements=11,gridRows=2,maxEntryCount=16
[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] GameNetworkManager.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:251 pos:251
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby currentSceneName=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for zerg
[Info   : Unity Log] Applying persistent ballot of votes for LocalUser 雨中冒险2.
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from zerg
[Info   : Unity Log] Accepting vote from zerg
[Info   : Unity Log] <style=cEvent>zerg connected.</color>

**Does the error occur when only using BetterUI and no other mods?**
Only BetterUI

**BetterUI Version**
V2.0.3

**Additional information**

**Comment by xoxfaby** [comment]
Fixed, it might take some time for mod managers to be able to see the new version
