### ISSUE TITLE
Item Scores do not work

### ISSUE THREAD

**Issue by zachmmeyer** [xoxfaby/BetterUI#53]
**Describe the bug**
Item Scores do not work. Where the mod would calculate out the item score, the ternary operator shows false and just appends 0 to the Item Score.
This is using the default config values.

**Link your log file**
[LogOuput.log](https://github.com/xoxfaby/BetterUI/files/6361854/LogOuput.log)

**Does the error occur when only using BetterUI and no other mods?**
No other mods are loaded except the dependencies.

**BetterUI Version**
v2.0.4

**Additional information**
No other information to submit at this time.
I can try and figure out what's going on, but RoR2 modding is not my forte.

**Comment by xoxfaby** [comment]
ah yes, the game changed when itemdefs are loaded so the loading of all the individual scores now needs to happen at a later time, this should be an easy fix when I'm able to get to it.
