### ISSUE TITLE
[suggestion] Crit Multiplier Stat

### ISSUE THREAD

**Issue by milkev** [xoxfaby/BetterUI#57]
**What feature would you like added to BetterUI?**
Crit Multiplier as an option in the stat display. I dont believe crit multiplier is modified in vanilla (its been a while since ive played vanilla, i could be wrong), but there are a couple mods that do modify the crit multiplier, and it would be great to see what its at.

**Comment by xoxfaby** [comment]
This is not a stat that exists so unfortunately this can't be done.
