### ISSUE TITLE
Visual bug with BetterUI and Photo Mode

### ISSUE THREAD

**Issue by doomdoze** [xoxfaby/BetterUI#59]
**Describe the bug**
Visual glitch happens to UI when i'm going in and out of photo mode inside Void Fields. Looks like empty bars are being added to the UI

**Link your log file**
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/6556717/LogOutput.log)

You can find your log file under `Risk of Rain 2/BepInEx/LogOutput.log`

**Does the error occur when only using BetterUI and no other mods?**
It is tied to PhotoMode

**BetterUI Version**
2.2.0

**Additional information**

**Comment by ethall** [comment]
I tried to duplicate and was successful. However, the same issue occurs when playing the game with only the PhotoMode mod installed.

I would suggest submitting a [PhotoMode Issue](https://gitlab.com/cwmlolzlz/ror2photomode/-/issues) and linking back to this one for context.

Additionally, this bug applies generally to the entire "Monsters & Monsters' Items" interface and is not level dependent. See the _PhotoMode_ section below for more information.

# BetterUI + PhotoMode

Reproduced the issue with BetterUI and PhotoMode (plus dependencies) installed.

| Mod | Version |
| --- | --- |
| BepInExPack | 5.4.9 |
| R2API | 3.0.43 |
| BetterUI | 2.2.0 |
| HookGenPatcher | 1.2.1 |
| PhotoMode | 1.1.0 |

## Log
[LogOutput_BetterUI+PhotoMode.log](https://github.com/xoxfaby/BetterUI/files/6603131/LogOutput_BetterUI%2BPhotoMode.log)

## Photo
![BetterUI+PhotoMode](https://user-images.githubusercontent.com/6527226/120902940-22788700-c611-11eb-8960-6783013ed663.jpg)

---

# PhotoMode

Reproduced the issue with only PhotoMode (plus dependencies) installed. It is not level dependent and be seen easily by using the Artifact of Evolution.

| Mod | Version |
| --- | --- |
| BepInExPack | 5.4.9 |
| R2API | 3.0.43 |
| HookGenPatcher | 1.2.1 |
| PhotoMode | 1.1.0 |

## Steps
1. Launch RoR2 with above mods active.
2. Enter a new singleplayer lobby.
3. Select any character and difficulty.
4. Activate the Artifact of Evolution.
5. Start the game.
6. Enter and exit photo mode a few times.
Note that the number of "Monsters & Monsters' Items" interface elements doubles every time you repeat this step.
The interface fixes itself when starting another stage via restart or teleporter/portal.

## Log
[LogOutput_PhotoMode.log](https://github.com/xoxfaby/BetterUI/files/6603135/LogOutput_PhotoMode.log)

## Photo
![20210605155406_1](https://user-images.githubusercontent.com/6527226/120904017-bea58c80-c617-11eb-803e-3d070ce52f79.jpg)

![PhotoMode](https://user-images.githubusercontent.com/6527226/120902941-23111d80-c611-11eb-9802-8b4c78c72ce7.jpg)
