### ISSUE TITLE
Scrapper taking wrong items

### ISSUE THREAD

**Issue by g0shu** [xoxfaby/BetterUI#6]
Only started happening after I installed this mod.
Here's the list of mods I have installed https://i.imgur.com/UyVPlf0.png
Here's the example of it happening https://www.youtube.com/watch?v=GY1WSeEP9Jw
And in my config I've set `SortOrderScrapper = S1i`.

**Comment by g0shu** [comment]
Just to make sure betterui is the cause, tried disabling `SortItemsScrapper` and it did fix the issue.

**Comment by xoxfaby** [comment]
Was this on 1.2.0?

Multiplayer or singleplayer?

**Comment by g0shu** [comment]
1.2.0 and singleplayer.

**Comment by xoxfaby** [comment]
I can't reproduce this so I am assuming it's a mod conflict. Could you try if it still happens with no other mods enabled?

**Comment by g0shu** [comment]
is there a way to force a scrapper spawn? i was considering going through all the mods 1 by 1 but looking for it every time is a pain

**Comment by xoxfaby** [comment]
I actually don't know. When I test I use rorcheats, give myself a bunch of items and run through the map looking for a scrapper. If there is none, I skip the stage.

**Comment by g0shu** [comment]
got it it break again with no other mods installed. well except cheats. the culprit is `SortOrderCommand`. so to reproduce:
1. make a fresh modman profile
2. install betterui and rorcheats.
3. set `SortOrderCommand` to `i`
4. give yourself monster tooth and ceremonial dagger in that order
5. try scrapping a dagger and receive a white scrap.

**Comment by xoxfaby** [comment]
Are you sure you mean `SortOrderCommand` ?

**Comment by g0shu** [comment]
yes https://i.imgur.com/LOI6luF.png

**Comment by xoxfaby** [comment]
If this patch does not fix the bug, feel free to reopen this.

**Comment by g0shu** [comment]
It's working fine now, but putting "SCRAPPER_CONTEXT" in chat on every use. is that intentional? thank you for the replies and a quick fix btw!

**Comment by xoxfaby** [comment]
oops I left my debug stuff in the code on accident. Will fix quickly haha
