### ISSUE TITLE
betterUI is throwing errors when trying to show item descriptions of items spawned on display for the chest shop of BiggerBazaar

### ISSUE THREAD

**Issue by xXxuser69420edgelordxXx** [xoxfaby/BetterUI#62]
**Describe the bug**
-See Title
-Only happens in singleplayer or for the host in multiplayer. For connected players it functions as normal, i.e they can read the descriptions of the items on display
-Happens with and without BetterAPI. Dont know if that really matters but i thought i'd test anyway.

**Link your log file**
-sure
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/6850822/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**
It specifically happens with biggerbazaar

**BetterUI Version**
-2.3.0

**Additional information**
Other mods used:
-BepInExPack v5.4.9
-R2API v3.0.44
-HookGenPatcher v1.2.1
-BiggerBazaar v1.12.13

**Comment by xoxfaby** [comment]
This is really old and I think BiggerBazaar addressed this, if not, please reopen this issue.
