### ISSUE TITLE
Crash when opening the essence of an item

### ISSUE THREAD

**Issue by Shasoleosh** [xoxfaby/BetterUI#67]
**Describe the bug**
Open any essences of the item that fall out when the artifact "Artifact of Command" is enabled. The game breaks down and crashes to the desktop.

**Link your log file**
Sorry, it's empty

**Does the error occur when only using BetterUI and no other mods?**
Yes  

**BetterUI Version**
v2.3.1

**Comment by Shasoleosh** [comment]
Oh, I've already figured out what the problem was!

**Comment by xoxfaby** [comment]
What was the issue?

**Comment by Shasoleosh** [comment]
Completely reinstalled RoR2
