### ISSUE TITLE
Mountain Shrine counter is not networked

### ISSUE THREAD

**Issue by SOMSTATE** [xoxfaby/BetterUI#68]
When a player activates a mountain shrine only the host will be able to see the counter, for the rest of the players it remains at 0.

**Comment by xoxfaby** [comment]
Yes this is a limitation of the game and not BetterUI

**Comment by milkev** [comment]
im not familiar with ror2 modding, but is it possible for a mod to send its own custom networking packet? or is this being limitted by something else?

**Comment by xoxfaby** [comment]
It is possible
