### ISSUE TITLE
Regex is matching weird for critdamage

### ISSUE THREAD

**Issue by Bubbet** [xoxfaby/BetterUI#71]
https://github.com/xoxfaby/BetterUI/blob/6e70f5abcd1e339e0ea02cb16df9801afa09568f/ModComponents/StatsDisplay.cs#L44

When using this stat the statsdisplay looks like Crit Damage: 0damage which means its matching $crit and putting in the wrong stat.

**Comment by Bubbet** [comment]
maybe swap it around and have the stat be $damagecrit ?

**Comment by SupersonicNK** [comment]
I think $critdamage makes more sense. 
Thankfully, the issue can also be fixed by swapping lines 44 and 43, as that would check and replace $critdamage before looking for $crit.

**Comment by alsimoneau** [comment]
Reverse sorting the dictionary keys before using them to build the regex string would fix and future proof the code.

**Comment by xoxfaby** [comment]
Fixed by d45585c8de6b7b40edd77db4ab79ce8dd53e7f51
