### ISSUE TITLE
[Suggestion!] Printers Scrappers & Shrines

### ISSUE THREAD

**Issue by EmuLegs** [xoxfaby/BetterUI#8]
**What feature would you like added to BetterUI?**
Hello me again, this is kinda out of scope... But, 
Could you add settings for faster 3d printers, chance shrines and scrapers please? 

Probs best to default them to off :)?

**Comment by xoxfaby** [comment]
For now I would say this is out of scope. Both because it's not a UI improvement and it actually has balance implications. Also I'm pretty sure a mod for this already exists.
