### ISSUE TITLE
NRE Spam on run end screen

### ISSUE THREAD

**Issue by CubularMonoxide** [xoxfaby/BetterUI#85]
**Describe the bug**
When the end of run screen is shown, the console begins spamming NREs, lagging the game immensely and preventing end of run stats from being shown.

**Link your log file**
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/8338655/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**
Yes.

**BetterUI Version**
2.5.0

**Additional information**
I have tested this on player death and after escaping the moon, both of which triggered this bug. I have not tested obliteration or the void ending.

**Comment by xoxfaby** [comment]
fixed by 4d54b1e
