### ISSUE TITLE
Dying Messes The Post-Game Report Up Completely

### ISSUE THREAD

**Issue by Ironiia** [xoxfaby/BetterUI#86]
**Describe the bug**
Everytime i die with BetterUI, in the post-game report it shows the same postgame report for a commander dying to a gunner turret. and the screen is also white, and the frames drop alot, the only way to exit said screen is pressing escape and quitting to menu or desktop. Happens in both single- and muliplayer.

**Link your log file**
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/8338999/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**
It does indeed happen when i only use BetterUI

**BetterUI Version**
I am currently using the newest version 2.5.0

**Additional information**
Here's a Screenshot of how it looks in the post-game report
![Skærmbillede 2022-03-24 070109](https://user-images.githubusercontent.com/102279529/159856509-85c1f96e-7310-4654-8917-d1290da62ea0.jpg)

**Comment by xoxfaby** [comment]
Newest version of BetterUI is 2.5.1, this is fixed.

**Comment by Ironiia** [comment]
well i'll damned, that was quick, thanks
