### ISSUE TITLE
Item descriptions inside the "pick your items" artifact are wrong for all rarities with other item mods

### ISSUE THREAD

**Issue by CanDoKen** [xoxfaby/BetterUI#87]
**Describe the bug**
When playing on "pick your items" using that in-game artifact, all the item descriptions don't match what the image of the item is when you hover over them. We do have the TeammateRevival mod which added items.

**Link your log file**
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/8339585/LogOutput.log)

**Does the error occur when only using BetterUI and no other mods?**
No, the bug doesn't occur.

**BetterUI Version**
2.5.1

**Comment by xoxfaby** [comment]
The log you sent shows no other mods installed so I'm assuming you sent the wrong log.

**Comment by CanDoKen** [comment]
I apologize, that was the log from my test with no other mods running, one moment.

**Comment by xoxfaby** [comment]
Okay. A log without the issue occurring isnt' really helpful. My guess is you have another command mod installed that is messing with the command menu and creating incorrect tooltips. The solution is to remove that mod.

**Comment by CanDoKen** [comment]
[LogOutput.log](https://github.com/xoxfaby/BetterUI/files/8339640/LogOutput.log)

**Comment by xoxfaby** [comment]
this is a bug with BetterCommandMenu, not BetterUI

**Comment by xoxfaby** [comment]
additionally, BetterUI already does everything BetterCommandMenu does

**Comment by CanDoKen** [comment]
Oh I see, thank you so much. We will be removing BetterCommandMenu right away!
