### ISSUE TITLE
Tooltips don't display in the command menu if CountersHideOnZero is set to true.

### ISSUE THREAD

**Issue by g0shu** [xoxfaby/BetterUI#9]
**Describe the bug**
![](https://i.imgur.com/FzuoeXe.jpeg)
![](https://i.imgur.com/vgQ1lvn.jpeg)

**What other mods do you use**
Tested on a fresh profile with no other mods except ItemStats.

**BetterUI Version**
1.3.0

**Comment by xoxfaby** [comment]
Interesting, it looks like maybe the tooltip provider doesn't work unless I put *some* other visual component into the button, I will test this and fix it quickly.
