### ISSUE TITLE
Mention that Leeching Seed is affected by proc coefficient in its base description

### ISSUE THREAD

**Issue by RandomNerd1** [xoxfaby/BetterUI#92]
**What feature would you like added to BetterUI?**

I think a good amount of players still aren't aware of this, maybe it'd be a good idea to add a little blurb in the item's description that mentions that Leeching Seed doesn't give you 1 HP flat no matter the hit, but that it heals you based on the proc coefficient of the attack that procs it?

**Comment by xoxfaby** [comment]
This is sort of already done with the skill proc info

**Comment by xoxfaby** [comment]
I'm planning to eventually add a module that will replace inaccurate item descriptions, maybe it could also include info like this in applicable items

**Comment by RandomNerd1** [comment]
> I'm planning to eventually add a module that will replace inaccurate item descriptions, maybe it could also include info like this in applicable items

That sounds great!

> This is sort of already done with the skill proc info

Sort of, but because of the way it's worded, I think lots of players simply figure it's a guaranteed 1 HP per hit, and also aren't aware that the game even deals at all in increments of HP smaller than 1, so even if they did take coeffs into account, might assume the game would round up to 1 when the calculated value would be less than 1.

**Comment by xoxfaby** [comment]
No I'm saying if you hover of your skills while having a seed it calculates the exact HP you will get

**Comment by RandomNerd1** [comment]
> No I'm saying if you hover of your skills while having a seed it calculates the exact HP you will get

Oh, I didn't realize that! Okay then, that's probably good enough.
