### ISSUE TITLE
Rose Buckler repeats "armor" in its description pointlessly

### ISSUE THREAD

**Issue by RandomNerd1** [xoxfaby/BetterUI#94]
**Describe the bug**

Sorry for not including all the info asked for, but this is an extremely simple thing, so I seriously doubt it's necessary: Rose Buckler will say something like "Armor: 30 Armor" when telling you its ultimate effect based on your stacks, but the second "Armor" is redundant.

**Comment by xoxfaby** [comment]
Don't think I'm changing this, this is because of how the stats are formatted.
